export const sagaActions = {
  FETCH_IMAGES_SAGA: "FETCH_IMAGES_SAGA",
  FETCH_IMAGE_SAGA: "FETCH_IMAGE_SAGA",
  FETCH_IMAGES_PORTRAIT_SAGA: "FETCH_IMAGES_PORTRAIT_SAGA",
  FETCH_IMAGES_LANDSCAPE_SAGA: "FETCH_IMAGES_LANDSCAPE_SAGA",
  FETCH_IMAGES_SNAKES_SAGA: "FETCH_IMAGES_SNAKES_SAGA",
  FETCH_IMAGES_CARS_SAGA: "FETCH_IMAGES_CARS_SAGA",
};
